# Drops existing tables, recreates them and executes import.sql
spring:
  # Settings for the oracle connection
  datasource:
    url: jdbc:oracle:thin:@TEST
    username: ja_api
    password: Propapi$6200
    tns: C:/Oracle12c/product/12.1.0/client_2/network/admin
    object: test

# sample -> https://github.com/indrabasak/spring-tls-example
server:
  connection-timeout: 60000
  port: 443
  ssl:
    enabled: true
    key-store: leon_test.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: leon
#    trust-store: classpath:foo.jks
#    trust-store-password: password

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /health_check

ja:
  http:
    auth-token-header-name: Authorization
    auth-token: 'YNN8TPLUFQ7lRGlMNxt8M21GhpCGVh7wHkPChG19m8Ai9voTzRpoYDr2KMfCOdjb'


#jackson:
#  mapper:
#    accept_case_insensitive_properties: true

logging:
  path: ./
  file: ja_int.log
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.data.integration: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
