# Drops existing tables, recreates them and executes import.sql
spring:
  # Settings for the oracle connection
  datasource:
    url: jdbc:oracle:thin:@TEST
    username: ja_api
    password: Propapi$6200
    tns: C:/Oracle12c/product/12.1.0/client_2/network/admin
    object: test

# sample -> https://github.com/indrabasak/spring-tls-example
server:
  port: 443
  ssl:
    enabled: true
    key-store: tmp.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /health_check

#jackson:
#  mapper:
#    accept_case_insensitive_properties: true

logging:
  path: ./
  file: cama.log
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.data.integration: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  appenders:
#  - type: file
#    currentLogFilename: ./cama.log
#    archivedLogFilenamePattern: /var/log/paas/console.log-%d.gz
#    archivedFileCount: 7
