# Drops existing tables, recreates them and executes import.sql
spring:
  # Settings for the oracle connection
  datasource:
    url:
      jdbc:oracle:thin:@TEST
    username:
      ja_api
    password:
      Propapi$6200
    driver-class-oracle:
      jdbc:
        driver:
          OracleDriver
  salt:

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /

jackson:
  mapper:
    accept_case_insensitive_properties: true