# Drops existing tables, recreates them and executes import.sql
spring:
  # Settings for the oracle connection
  datasource:
    url: jdbc:oracle:thin:@TEST
    username: ja_api
    password: Propapi$6200
    tns: C:/Oracle12c/product/12.1.0/client_2/network/admin
    object: test
  salt:

server:
  port: 8443
  ssl:
    key-store: tmp.p12
    key-store-password: 123456
    keyStoreType: PKJACS12
    keyAlias: tomcat

management:
  endpoints:
    web:
      base-path: /

jackson:
  mapper:
    accept_case_insensitive_properties: true