PARID            NOT NULL VARCHAR2(30)
TAXYR            NOT NULL NUMBER(4)
OWNSEQ           NOT NULL NUMBER(3)
SEQ              NOT NULL NUMBER(3)
OWN1                      VARCHAR2(205)
OWN2                      VARCHAR2(205)
CAREOF                    VARCHAR2(60)
ADDRTYPE                  VARCHAR2(1)
ADRNO                     NUMBER(10)
ADRADD                    VARCHAR2(6)
ADRDIR                    VARCHAR2(2)
ADRSTR                    VARCHAR2(30)
ADRSUF                    VARCHAR2(8)
ADRSUF2                   VARCHAR2(8)
CITYNAME                  VARCHAR2(40)
STATECODE                 VARCHAR2(2)
COUNTRY                   VARCHAR2(30)
POSTALCODE                VARCHAR2(10)
UNITDESC                  VARCHAR2(10)
UNITNO                    VARCHAR2(10)
ADDR1                     VARCHAR2(80)
ADDR2                     VARCHAR2(80)
ADDR3                     VARCHAR2(80)
ZIP1                      VARCHAR2(5)
ZIP2                      VARCHAR2(4)
PCTOWN                    NUMBER(7,4)
SALEKEY                   NUMBER(8)
OWNTYPE1                  VARCHAR2(3)
OWNTYPE2                  VARCHAR2(3)
OWNTYPE3                  VARCHAR2(3)
OWNTYPE4                  VARCHAR2(3)
HIDENAME                  VARCHAR2(1)
MARSTAT                   VARCHAR2(1)
OWNNUM                    VARCHAR2(20)
BOOK                      VARCHAR2(8)
PAGE                      VARCHAR2(8)
USER4                     VARCHAR2(20)
IASW_ID                   NUMBER