PARID            NOT NULL VARCHAR2(30)
TAXYR            NOT NULL NUMBER(4)
OWNSEQ           NOT NULL NUMBER(3)
SEQ              NOT NULL NUMBER(3)
OWN1                      VARCHAR2(205)
OWN2                      VARCHAR2(205)
PCTOWN                    NUMBER(7,4)
SALEKEY                   NUMBER(8)
OWNTYPE1                  VARCHAR2(3)
OWNTYPE2                  VARCHAR2(3)
OWNTYPE3                  VARCHAR2(3)
OWNTYPE4                  VARCHAR2(3)
HIDENAME                  VARCHAR2(1)
MARSTAT                   VARCHAR2(1)
BOOK                      VARCHAR2(8)
PAGE                      VARCHAR2(8)
USER4                     VARCHAR2(20)
IASW_ID                   NUMBER